### ISSUE TITLE
Doesn't appear to like resources with the same name in multiple templates

### ISSUE THREAD

**Issue by willhallam** [stelligent/cfn_nag#103]
Using the same resource name in multiple templates produces a warning:
/usr/local/rvm/gems/ruby-2.2.8/gems/cfn-model-0.1.16/lib/cfn-model/parser/cfn_parser.rb:121: warnin
g: already initialized constant TagDisk
/usr/local/rvm/gems/ruby-2.2.8/gems/cfn-model-0.1.16/lib/cfn-model/parser/cfn_parser.rb:121: warnin
g: previous definition of TagDisk was here

In this case I have multiple templates which call the same utility Lambda function, which seems pretty "valid".

**Comment by erickascic** [comment]
Sorry for the delay.  Day job gets in the way :)

If multiple "templates" == "resources", then I think you should be good with 0.3.19.

The test template I used to reproduce the irritating warning is here:
https://github.com/stelligent/cfn-model/blob/master/spec/test_templates/yaml/custom_resource/custom_resource.yml

@willhallam let me know if you are good or the bug is different than what I thought it was.  Thanks for finding!

p.s. if you have any general requirements for scanning custom resources, would love to hear them.

**Comment by willhallam** [comment]
@erickascic - I am good, the warning has disappeared.

Best,

Will

**Comment by willhallam** [comment]
Closing.
