### ISSUE TITLE
cfn_nag should be lintable

### ISSUE THREAD

**Issue by jeffb4** [stelligent/cfn_nag#122]
It should be possible to run a linter such a rubocop over the cfn_nag code to keep code readable as the project continues.

This issue is intended as an umbrella for commits to point to. When we're able to run a linter in the test script and fail based on it, then this issue will be closable

**Comment by jeffb4** [comment]
There are a LOT of long lines in certain folders, I've done some targeted increase of line length to 120 where that's necessary.

I understand not everyone loves 80 characters, but if we (@erickascic ) can decide on a value between 80-100 for the project generally, that'd be great. Longer lines become difficult to parse and maintain, even if they display just fine on modern IDEs.

**Comment by jeffb4** [comment]
I've been putting simple, small comments in front of classes for the most minimal of documentation. New maintainers could help our yard doc situation by fleshing the comment docs out

**Comment by jeffb4** [comment]
https://github.com/stelligent/cfn_nag/tree/master/lib/cfn-nag/custom_rules does not use snake case filenames, which is Ruby standard practice. I turned off the cop for that in that directory.

**Comment by jeffb4** [comment]
Method length cop by default with rubocop is extremely short (10 lines). In my experience, this is a good limit and most methods can be refactored that short, but we can bump that up a little if needed. I'd recommend less than 15 lines.

**Comment by erickascic** [comment]
1. the rule filename convention is because those names match class names which don't admit underscores
2. my philosophy on long lines is to avoid them but them and have top-down code but.... there are just times when it stuff looks more readable on the same line.  100 is fine by me
3. the line length one... yea 15 is fine although a bunch of linear code > 15 doesn't bother me _so_ much (even though it probably does deserve deocomp).  that said i'm more concerned about ccm than line numbers....
