### ISSUE TITLE
Use JMESPath instead of jq

### ISSUE THREAD

**Issue by nikolay** [stelligent/cfn_nag#19]
Although not as powerful as jq, [JMESPath](http://jmespath.org/) can do most of the stuff already and it's the tool of choice of AWS-CLI via the `--query` option. In addition, it's [cross-language](http://jmespath.org/libraries.html) and can be used within Ruby without the need to require a binary dependency.

**Comment by erickascic** [comment]
Cool, yea will look into this when I have some spare cycles.  The jq queries are pretty much out of hand as-is, so a re-work of the parsing is probably in order anyways.

**Comment by erickascic** [comment]
Version 0.1.7 has experimental support for jmespath.  Any of the 0.1.x releases don't rely upon jq anymore.... doing anything moderately complicated with jq gets out of hand quickly so I focused on developing cfn-model to abstract the underlying template and to make rule development in Ruby much simpler.  So that being said, I would say the best way to develop rules from hereon is to use cfn-model but..... I understand not everybody is comfortable writing Ruby code, so I'm adding jmespath support.

The way cfn templates are structured with the logical resource id's as keys..... I couldn't figure a way in jmespath to flatten things so the id of a violating resource can be found so.... the i flatten the id into the resource definition before passing to jmespath.  I promise I will have some documentation on how to do this in the near future (and the multitude of underlying changes for the move to 0.1.x)

To use this, drop a file named *jmespath.rb into the "rules directory" specified from the command line.  The rule writing is similar to old cfn-nag with warning and failure definitions.  See here for an example:  

https://github.com/stelligent/cfn_nag/blob/master/lib/cfn-nag/custom_rules/ebs_volumes_jmespath.rb

**Comment by nikolay** [comment]
@erickascic Great job! Thank you!
