### ISSUE TITLE
Security groups custom rules

### ISSUE THREAD

**Issue by sreddi620** [stelligent/cfn_nag#280]
I have configured the following custom rules, however these rules are not working correctly. Can you please review the rules and correct me.
Rule1: Identify any security group with ports 22 and 3389 as ingress
https://github.com/sreddi620/CFN_NAG_Rules/blob/master/SecurityGroupIngressPort22and3389Rule.rb
Rule2: Identify any security group without port 443 as ingress
https://github.com/sreddi620/CFN_NAG_Rules/blob/master/SecurityGroupwithOutPort443Rule.rb

**Comment by erickascic** [comment]
For the 22/3389 rule - i believe the first problem is that you are using assignment instead of comparison in the select coroutine (ingress.toPort = 22 instead of ingress.toPort == 22).

For the 443 rule - I'm not 100% sure, but the first thing I would test is whether you should be comparing to 443 the number, or "443" the string.  you might try converting with to_s and then comparing to "443".

**Comment by sreddi620** [comment]
Hi,

I tried correcting my rules with your suggestions. However I am not able to
use these rules correctly. Instead of this conversation, is there a
possibility to have a zoom meeting to discuss and resolve all of my issues
at a time.
Please provide me your email address to contact you.

**Comment by sreddi620** [comment]
Hi,

Small update. Instead of to_s, the rules are working by placing to_i.

**Comment by erickascic** [comment]
@sreddi620 I have a bit of time tonight - I'll send you some PRs for your rules (at least what i think you are trying to do with them)

**Comment by erickascic** [comment]
@sreddi620 i put out a PR.  you can email me directly if the rules still don't behave how you'd like (eric.kascic@stelligent.com)
