### ISSUE TITLE
Custom cfn_nag rule in lambda

### ISSUE THREAD

**Issue by foobar123-del** [stelligent/cfn_nag#287]
i have gone through all the documentation.
i want to integrate cfn_nag with aws codepipeline i have create cfn_nag function from lambda serverless repo and used the function in the pipeline and it is working perfect but the problem here i want to create a custom cfn_nag lambda function which can be used in pipeline but i am unable to find the documentation.
i am not sure where to place the custom rule  @kidbrax @PaulDuvall

**Comment by erickascic** [comment]
i'm not sure i follow.  you want to make changes to the cfn_nag function in the serverless repo?

**Comment by foobar123-del** [comment]
Yes i want to add custom rule

**Comment by erickascic** [comment]
@foobar123-del apologies on the delay. 

The SAR deployment of cfn_nag as-is doesn't really support custom rules (as far as I can tell - i implemented a good bit of the underlying components, but i didn't author the SAR code specifically).  This SAR deployment needs to be re-written to work with AWS's built-in support for Ruby.... and provide a hook for picking up rules (perhaps from S3).

I'm likely not going to have time/manpower to do this in the near future..... I guess in the meantime what I would suggest to you is to fork cfn-nag and https://github.com/stelligent/cfn-nag-pipeline.  Then I'd bake your custom rules into your fork of cfn-nag.... and push a lambda/SAR that references your cfn-nag instead of the stelligent one.
