### ISSUE TITLE
Configurable non-zero exit code for warnings

### ISSUE THREAD

**Issue by atkinsonm** [stelligent/cfn_nag#292]
I have a workflow that looks for the cfn_nag exit code to mark a step with one of three statuses: pass, warning, or fail. Sometimes I run cfn_nag and only warnings appear, which results in a zero/success code. However, for my workflow this could be considered a "false positive", showing a scan as having passed instead of showing a warning.

It would help me to have the ability to control whether failures exit with non-zero codes. That might not work for everyone, so perhaps a command line argument would allow a user to toggle this. The default behavior could be the same as it is now.

What would be _especially_ helpful is if each possible outcome had its own unique exit code. For example:
* 0: success, no warnings or failures
* 1: at least one warnings, no failures
* 2: at least one failure, and any number of failures including zero
* 3: theoretical other exit code indicating some failure to perform the scan

**Comment by erickascic** [comment]
@atkinsonm sorry on the delay.  

There is a --fail-on-warnings command line argument for cfn_nag..... I can't unconditionally makes warnings non-zero because it would break the existing interface..... I could add this exit code as a "mode" with an extra argument, but before I do, first confirm fail-on-warnings doesn't full meet your needs and....

if the output is in JSON - can you use jq to figure out the pass/fail workflow you need?

**Comment by atkinsonm** [comment]
@erickascic not a problem.

I must have missed the `--fail-on-warnings` argument since it doesn't appear to be documented in the readme. That said, this does seem like a duplicate of #84  (which I realized I had commented on several months ago but must not have remembered or seen that it was release). Apologies for the duplicate, it seems like my use case is already met.
