### ISSUE TITLE
Executing as lambda function

### ISSUE THREAD

**Issue by neilhunt1** [stelligent/cfn_nag#45]
Hi, can this be executed as a lambda function? This would be a more preferable serverless solution, no? It would also allow us to run this as part of a CodePipeline.

**Comment by erickascic** [comment]
Yep, I've shoe-horned it into a JRuby/Java based lambda for a client in the past.  There was some pain with custom rule loading (resolving files ruby style v. classloader issues) but alot has changed with the underlying rule loading since then.

We're looking into putting out a REST front-end in the near future but.... aside from that, having a pure Lambda for CodePipeline is a really good use case so you can call this direct from a pipeline (i.e. I'll try to put something out in the near future)

**Comment by erickascic** [comment]
AWS has released native Ruby support in Lambda now....
