### ISSUE TITLE
Python support for custom cfn_nag rules

### ISSUE THREAD

**Issue by soansgla** [stelligent/cfn_nag#462]
Can we develop custom cfn_nag rules in python instead of ruby ? Is there any documentation around that if thats possible?

**Comment by erickascic** [comment]
@soansgla unfortunately this is not supported currently.  

a few random thoughts in this area:
1. i could support simple jmespath based rule fairly easily (most of the code is in there to support this alread)
2. i could support writing rules in javascript because there are js interpreters that are implemented in ruby
3. i know of no such python interpreter in ruby which is where the wheels fall off in the current implementation. any solution that doesn't involve a total rewrite likely involves some difficult hacky magic to cross process boundaries? dunno
4. i've kicked around the idea of what it would be like to re-implements cfn_nag in the GraalVM and then naturally allow for rules written in a variety languages on top (including python, ruby, js)
