### ISSUE TITLE
KMS Enable Key Rotation parameter has to exist and be true

### ISSUE THREAD

**Issue by isuftin** [stelligent/cfn_nag#467]
According to [CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kms-key.html#cfn-kms-key-enablekeyrotation), the KMS KeyRotation parameter is optional and can be true or false. However, cfn_nag [has it coded](https://github.com/stelligent/cfn_nag/blob/master/lib/cfn-nag/custom_rules/KMSKeyRotationRule.rb#L30-L32) that the EnableKeyRotation parameter MUST exist in the template and MUST be set to true.

Is this an oversight or ... ?

**Comment by isuftin** [comment]
https://github.com/stelligent/cfn_nag/issues/217

It's unclear why this would be a feature?

**Comment by mcbanderson** [comment]
This is intentional. `cfn_nag` identifies potentially insecure resource configurations, and per [AWS Documentation](https://docs.aws.amazon.com/kms/latest/developerguide/rotate-keys.html) (and security best practices), it is recommended that you avoid extensive encryption key reuse. The best way to do so is to enable automatic key rotation.

If you wish to disable this requirement on a specific resource, you can [suppress the rule on a per-resource basis.](https://github.com/stelligent/cfn_nag#per-resource-rule-suppression)
