### ISSUE TITLE
Tool fails with error "No implicit conversion of String into Integer"

### ISSUE THREAD

**Issue by dbubovych** [stelligent/cfn_nag#88]
Here is a stack trace:

 /usr/local/bundle/gems/cfn-model-0.1.11/lib/cfn-model/model/references.rb:19:in
 `[]': no implicit conversion of String into Integer (TypeError)
        from /usr/local/bundle/gems/cfn-model-0.1.11/lib/cfn-model/model/references.rb:19:in > > `resolve_security_group_id'
        from /usr/local/bundle/gems/cfn-model-0.1.11/lib/cfn-model/model/cfn_model.rb:57:in `find_security_group_by_group_id'
        from /usr/local/bundle/gems/cfn-model-0.1.11/lib/cfn-model/parser/load_balancer_parser.rb:6:in `block in parse'
        from /usr/local/bundle/gems/cfn-model-0.1.11/lib/cfn-model/parser/load_balancer_parser.rb:5:in `each'
        from /usr/local/bundle/gems/cfn-model-0.1.11/lib/cfn-model/parser/load_balancer_parser.rb:5:in `map'
        from /usr/local/bundle/gems/cfn-model-0.1.11/lib/cfn-model/parser/load_balancer_parser.rb:5:in `parse'
        from /usr/local/bundle/gems/cfn-model-0.1.11/lib/cfn-model/parser/cfn_parser.rb:56:in `block in post_process_resource_model_elements'
        from /usr/local/bundle/gems/cfn-model-0.1.11/lib/cfn-model/parser/cfn_parser.rb:50:in `each'
        from /usr/local/bundle/gems/cfn-model-0.1.11/lib/cfn-model/parser/cfn_parser.rb:50:in `post_process_resource_model_elements'
        from /usr/local/bundle/gems/cfn-model-0.1.11/lib/cfn-model/parser/cfn_parser.rb:42:in `parse'
        from /usr/local/bundle/gems/cfn-nag-0.3.11/lib/cfn-nag/cfn_nag.rb:64:in `audit'
        from /usr/local/bundle/gems/cfn-nag-0.3.11/lib/cfn-nag/cfn_nag.rb:48:in `block in audit_aggregate_across_files'
        from /usr/local/bundle/gems/cfn-nag-0.3.11/lib/cfn-nag/cfn_nag.rb:45:in `each'
        from /usr/local/bundle/gems/cfn-nag-0.3.11/lib/cfn-nag/cfn_nag.rb:45:in `audit_aggregate_across_files'
        from /usr/local/bundle/gems/cfn-nag-0.3.11/lib/cfn-nag/cfn_nag.rb:29:in `audit_aggregate_across_files_and_render_results'
        from /usr/local/bundle/gems/cfn-nag-0.3.11/bin/cfn_nag_scan:32:in `<top (required)>'
        from /usr/local/bundle/bin/cfn_nag_scan:23:in `load'
        from /usr/local/bundle/bin/cfn_nag_scan:23:in  `main'

**Comment by erickascic** [comment]
Can you submit an example of the load balancer resource that is causing this parse error?

**Comment by arecker** [comment]
I think I've found the problem.  The docs say the [SecurityGroup
type](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-elb.html#cfn-ec2-elb-securitygroups)
is a list.  This may be an actual list of individual resource IDs _or_
a `CommaDelimitedList`.

> An array of literal strings that are separated by commas. The total
> number of strings should be one more than the total number of
> commas. Also, each member string is space trimmed.
>
> For example, users could specify "test,dev,prod", and a Ref will
> result in ["test","dev","prod"].

The problem is that Cfn Nag assumes this will always be an array when
it [maps over the list to resolve the
references](https://github.com/stelligent/cfn-model/blob/master/lib/cfn-model/parser/load_balancer_parser.rb#L5).
Under working conditions when mapping over what is expecting,
something like `[{ 'Ref' => 'GroupOne' }, { 'Ref' => 'GroupTwo' }]`,
the map returns hashes which work fine when it checks the hash
[here](https://github.com/stelligent/cfn-model/blob/master/lib/cfn-model/model/references.rb#L19).

In the breaking case, mapping over a single hash pointing to a
CommaDelimitedList causes `map` to return the bogus value `['Ref',
'MyGroups']`.  And performing `['Ref', 'MyGroups']['Ref']` raises the
error because it is an array, not a hash.

I'm pretty sure that [this block of
code](https://github.com/stelligent/cfn-model/blob/master/lib/cfn-model/model/references.rb#L19-L28)
just needs to be modified to give up on this case.

**Comment by erickascic** [comment]
@arecker thx for doing the foot work on this.  that list "type" has been a bane to the validation (or one of them).... I need to set aside a weekend and remove some of the "validation" that is going on since it's just not correct.  the point was to make life easier for downstream rule development (given a validated schema) but there are a number of variations that just are not being accounted for and rule developers can be more specific looking for badness

**Comment by Olegwitcher** [comment]
Hello ,
We have the same issue.
Waiting for fix.
Thank you.

**Comment by erickascic** [comment]
I wrongfully blamed the overzealous schema validation.  The post-processing parsing for ELB, ELBv2 and also ENI was broken in just the way @arecker mentioned, but had to fix things a little earlier in the call chain.

Version 0.3.12 has the fix that should make this go away.

The one extra warning to throw out at interested parties is that.... I've basically just made the error go away, but I haven't added any code to examine the referenced security groups.  I don't believe there is any way to do "static analysis" on those security groups given they are lists of literal security group ids.  i.e. the configuration of those security groups is not contained within the template under analysis so there is no way to analyze them (without making a call to AWS API).
